Increment13
T-V-N/gourlshortener pull request #11
Opened 2022-10-18 15:02 UTC by T-V-N

2022-10-22 18:44 UTC, lostsequence requested changes

2022-10-22 18:44 UTC, lostsequence commented on internal/middleware/auth/auth.go
> +				r.Header.Set("uid", hexValue[32:])
Лучше передай дальше не через header, а через request context

2022-10-22 18:44 UTC, lostsequence commented on internal/middleware/auth/auth.go
> +					http.Error(w, "Something went wrong", http.StatusBadRequest)
Лучше вернуть internalServerError, потому что тут дело не в реквесте

2022-10-22 18:44 UTC, lostsequence commented on internal/middleware/auth/auth.go
> +			valid, err := isValidCookie(cookie, cfg.SecretKey)
переменную лучше тоже назвать isValid, как в названии функции

2022-10-22 18:44 UTC, lostsequence commented on internal/storage/DBStorage.go
> +	conn, err := pgx.Connect(context.Background(), cfg.DatabaseDSN)
Лучше не создавать новый коннект на каждый запрос.
При старте приложения создай один коннекшн к базе и уже используй его. Не забудь его закрыть перед завершением main.
Используй pgxpool вместо pgx - он потокобезопасный.

2022-10-22 18:44 UTC, lostsequence commented on internal/storage/DBStorage.go
> +	_, err = conn.Exec(ctx, sqlStatement, uid, hash, url)
После того как из методов уйдет создание коннекшна, контекст не убирай, он пригодится.
Используй вместо обычных методов, методы с контекстом: ExecContext, QeryRowContext и т.д.

2022-10-22 18:44 UTC, lostsequence commented on internal/storage/DBStorage.go
> +	(uid varchar, hash varchar, original_url varchar);
Предлагаю немного понятней назвать колонки, например:
`user_uid, shorten_url/url_hash, original_url`

2022-10-22 18:44 UTC, lostsequence commented on internal/handler/handler.go
> +		}
Очень большая вложенность if, попробуй избавиться пожалуйста.
И в HandleShortenURL тоже

2022-10-22 18:44 UTC, lostsequence commented on internal/middleware/auth/auth.go
> +
Можно потестить auth, как с gzip

2022-10-25 16:41 UTC, T-V-N commented on internal/middleware/auth/auth.go
> +				r.Header.Set("uid", hexValue[32:])
посмотри пожалуйста.
Я не уверен в правильности подхода - пришлось делать ключ-структуру и проверять value на строку. Это норм?

2022-10-25 22:48 UTC, T-V-N commented on internal/storage/DBStorage.go
> +	_, err = conn.Exec(ctx, sqlStatement, uid, hash, url)
похоже, что pgxpool из коробки позволяет передать в себя контекст, все сработало без изменений кода

2022-10-25 22:56 UTC, T-V-N commented on internal/handler/handler.go
> +		}
убрал 1 уровень

2022-10-25 23:39 UTC, T-V-N commented on internal/storage/DBStorage.go
> +	conn, err := pgx.Connect(context.Background(), cfg.DatabaseDSN)
посмотри пожалуйста, правильно ли пихать отключение в log.Panic?

2022-10-27 18:11 UTC, lostsequence commented on internal/middleware/auth/auth.go
> +				r.Header.Set("uid", hexValue[32:])
Норм, можно просто type UIDKey string. Просто чтобы был отличен от built-in type https://pkg.go.dev/context#WithValue

2022-10-27 19:17 UTC, lostsequence commented on internal/storage/DBStorage.go
> +	conn, err := pgx.Connect(context.Background(), cfg.DatabaseDSN)
можно просто defer st.KillConn
Если интересно, почитай про стратегии graceful stop :)

2022-10-27 19:19 UTC, lostsequence commented on internal/storage/DBStorage.go
> +	_, err = conn.Exec(ctx, sqlStatement, uid, hash, url)
не так понял. Контекст нужен для методов. Чтобы когда прервался контекст http context, методы тоже прервали выполнение.

https://go.dev/doc/database/cancel-operations

2022-10-28 18:43 UTC, lostsequence approved these changes

2022-10-28 18:43 UTC, lostsequence commented on internal/middleware/gzip/gzip.go
> +	return err
тут можно просто в return g.Body.Close()

2022-12-02 12:50 UTC, merged