Increment3
T-V-N/gourlshortener pull request #4
Opened 2022-09-06 15:52 UTC by T-V-N

2022-09-12 20:03 UTC, lostsequence requested changes

2022-09-12 20:03 UTC, lostsequence commented on cmd/shortener/main.go
> +	fmt.Println("go!")
Этот код выполнится ?)

2022-09-12 20:03 UTC, lostsequence commented on cmd/shortener/main.go
> +	if err != nil {
Можно listenandserve в log.Panic() передать вместо проверки

2022-09-12 20:03 UTC, lostsequence commented on internal/storage/storage.go
> +	}
Данная проверка выглядит странно.
Если передадут пустую мапу у которой len == 0, то в принципе она ничем не отличается от пустой мапы, которой мы инициализируем стор до проверки.
Стоит проверить на nil. И чтобы просто так не создавать каждый раз мапу, можно её в else вынести:
```
if data == nil {
  storage.db = make(map[string]string)
} else {
  storage.db = data
}
```
или без ветвления еще короче

```
if data == nil {
  return &Storage{make(map[string]string)}
}

return &Storage{data}
```

2022-09-12 20:03 UTC, lostsequence commented on internal/handler/handler_test.go
> +			body: []byte(""),
можно добавить еще кейс, когда не пустой урл, а какой-нибудь с кривыми данными, типа "ht_t_p://google.com"

2022-09-12 20:03 UTC, lostsequence commented on internal/handler/handler_test.go
> +			request := httptest.NewRequest(http.MethodGet, "/"+tt.param, nil)
Перепиши пожалуйста без создания роутера.
Параметры можно передать через контекст.

```
ctx := chi.NewRouteContext()
ctx.URLParams.Add("urlHash", tt.param)
rctx := context.WithValue(request.Context(), chi.RouteCtxKey, ctx)
request = request.WithContext(rctx)
```

2022-09-12 20:03 UTC, lostsequence commented on internal/handler/handler.go
> +type URL struct {
Данная структура где-то используется ? Не нашел. Если нет, то лучше убрать.

2022-09-13 12:53 UTC, T-V-N commented on cmd/shortener/main.go
> +	fmt.Println("go!")
Нет. Поток будет заблокирован listen and serve и до fmt не дойдет =(

2022-09-13 12:55 UTC, T-V-N commented on cmd/shortener/main.go
> +	if err != nil {
Done.

2022-09-13 12:59 UTC, T-V-N commented on internal/handler/handler_test.go
> +			body: []byte(""),
done

2022-09-13 12:59 UTC, T-V-N commented on internal/storage/storage.go
> +	}
done

2022-09-13 13:05 UTC, T-V-N commented on internal/handler/handler_test.go
> +			request := httptest.NewRequest(http.MethodGet, "/"+tt.param, nil)
Done.

2022-09-13 13:11 UTC, T-V-N commented on cmd/shortener/main.go
> +	fmt.Println("go!")
done

2022-09-13 13:11 UTC, T-V-N commented on internal/handler/handler.go
> +type URL struct {
Done

2022-09-15 19:06 UTC, lostsequence approved these changes

2022-09-15 19:06 UTC, lostsequence commented on internal/handler/handler_test.go
> +			name: "Wrong URL passed",
Тут можно "empty url", а то один тест "wrong", другой "incorrect" :)

2022-09-15 19:06 UTC, lostsequence commented on internal/handler/handler_test.go
> +			h.ServeHTTP(w, request)
в принципе можно обойтись без serveHTTP, просто вызвать метод хендлера:
`hn.HandleGetURL(w, request)`

2022-09-15 19:10 UTC, lostsequence commented on internal/handler/handler.go
> +		panic(err.Error())
Паника - это жестковато. Давай прото ошибку залогаем )

2022-10-03 15:49 UTC, merged