Increment8
T-V-N/gourlshortener pull request #6
Opened 2022-10-04 13:45 UTC by T-V-N

2022-10-07 19:29 UTC, lostsequence requested changes

2022-10-07 19:29 UTC, lostsequence commented on cmd/shortener/main.go
file_storage/db - пустой файл, нужен ?

2022-10-07 19:29 UTC, lostsequence commented on internal/config/config.go
> +func InitTestConfig() (*Config, error) {
Инициализацию тестового конфига лучше вынести из "боевого" файлика к тестам

2022-10-07 19:29 UTC, lostsequence commented on cmd/shortener/main.go
> +	log.Panic(http.ListenAndServe(a.Config.ServerAddress, gzip.GzipHandle(router)))
Миддлварь лучше использовать с помощью router.Use, а в ListenAndServe передать router

2022-10-07 19:29 UTC, lostsequence commented on internal/middleware/gzip/gzip.go
> +		withGzNext := gziphandler.GzipHandler(next)
Лучше используй готовый миддлварь в chi, чтобы не тянуть лишние пакеты
https://go-chi.io/#/pages/middleware?id=compress

2022-10-07 19:29 UTC, lostsequence commented on internal/storage/storage.go
> +		if !scanner.Scan() {
Можно проверку в for перенести:
`for scanner.Scan() {...}`

2022-10-07 19:29 UTC, lostsequence commented on internal/storage/storage.go
> +		err = json.Unmarshal(lineBytes, &url)
можно переписать с помощью NewDecoder()

2022-10-07 19:29 UTC, lostsequence commented on internal/middleware/gzip/gzip.go
> +			r.Body = gz
Есть один нюанс связанный с gzip reader, он не закрывает underlaying reader.
По хорошему надо имплементировать интерфейс io.ReadCloser и в методе Close закрыть и gzip reader и body.

2022-10-07 19:29 UTC, lostsequence commented on internal/handler/handler.go
> +	}
Можно Marshal, Unmarshal заменить на NewEncoder().Encode(), NewDecoder().Decode()
Будет поменьше кода

2022-10-07 19:29 UTC, lostsequence commented on internal/handler/handler.go
>  		panic(err.Error())
Думаю не стоит паниковать и ронять сервис
Просто залогать ошибку

2022-10-07 19:29 UTC, lostsequence commented on internal/handler/handler_test.go
> +			resBody, _ := io.ReadAll(res.Body)
можно все данные получить напрямую из w:
w.Body.Bytes() вместо чтения боди
w.Code вместо res.StatusCode

2022-10-07 19:29 UTC, lostsequence commented on internal/handler/handler_test.go
> +
Добавь пожалуйста тесты на компрессию/декомпрессию

2022-10-07 19:29 UTC, lostsequence commented on cmd/shortener/main.go
> +		return
если паникуем, в принципе return думаю не нужен

2022-10-07 19:29 UTC, lostsequence commented on internal/handler/handler_test.go
>  			h.ServeHTTP(w, request)
Можно в принципе без ServeHTTP и HandlerFunc вызвать просто метод хендлера:
`hn.HandlePostURL(w, request)`

2022-10-09 15:50 UTC, T-V-N commented on cmd/shortener/main.go
Убрал

2022-10-09 15:50 UTC, T-V-N commented on internal/config/config.go
> +func InitTestConfig() (*Config, error) {
Сделано

2022-10-09 15:51 UTC, T-V-N commented on cmd/shortener/main.go
> +	log.Panic(http.ListenAndServe(a.Config.ServerAddress, gzip.GzipHandle(router)))
Сделано

2022-10-09 15:51 UTC, T-V-N commented on internal/middleware/gzip/gzip.go
> +		withGzNext := gziphandler.GzipHandler(next)
Сделано

2022-10-09 15:51 UTC, T-V-N commented on internal/storage/storage.go
> +		if !scanner.Scan() {
Сделано

2022-10-09 21:39 UTC, T-V-N commented on internal/handler/handler_test.go
> +
добавил тесты для сжатого и несжатого запросов. Оно?

2022-10-10 20:40 UTC, lostsequence requested changes

2022-10-10 20:40 UTC, lostsequence commented on internal/handler/handler.go
> +	}
Не так немного. Можно в NewDecoder передать сразу боди.
`err := json.NewDecoder(r.Body).Decode(&obj)`
Не надо вычитывать body

И так же NewEncoder:
`json.NewEncoder(w).Encode(shortenedURL)`

2022-10-10 20:40 UTC, lostsequence commented on internal/middleware/gzip/gzip.go
> +			r.Body = gz
не поправлен комментарий. Надо сделать свою реализацию io.ReadCloser, чтобы подменить Body.
В реализации метода Close закрыть и body и gzip reader

2022-10-10 20:40 UTC, lostsequence commented on internal/handler/handler_test.go
> +
Да, спасибо

2022-10-10 20:41 UTC, lostsequence commented on internal/middleware/gzip/gzip.go
> +		withGzNext := middleware.Compress(5)
Лучше использовать эту миддлварь явно в router.Use

2022-10-10 20:42 UTC, lostsequence commented on internal/middleware/gzip/gzip.go
> +		if !strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") {
middleware.Compress не проверяет header на accept-encoding ?

2022-10-18 17:37 UTC, lostsequence commented on internal/middleware/gzip/gzip.go
> +}
Надо реализовать методы `Close () error` и `Read (p []byte) (int, error)`
В методе Close закрыть два ридерера и вернуть ошибку
В качестве нового боди передать экземпляр структуры Gzip

2022-10-18 17:37 UTC, lostsequence approved these changes

2022-12-02 12:50 UTC, merged